name: gmm-vae
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.8
  - numpy=1.20.1
  - pandas=1.2.4 
  - pytorch=1.10.0
  - scipy=1.6.2
  - seaborn=0.11.1 
  - jupyterlab
  - pip
  - pip:
    - pytorch-lightning==1.5.0
    - scikit-learn==1.0.1
